@BookTracker.Api_HostAddress = http://localhost:5202

GET {{BookTracker.Api_HostAddress}}/weatherforecast/
Accept: application/json



###

GET {{BookTracker.Api_HostAddress}}/books
Accept: application/json

### Create Book
POST http://localhost:5202/books
Content-Type: application/json

{
  "title": "Dune",
  "author": "Frank Herbert",
  "year": 1965
}

### Delete Book
DELETE http://localhost:5202/books/1 

### Delete Book (not found)
DELETE http://localhost:5202/books/9999

### Update Book
PUT {{BookTracker.Api_HostAddress}}/books/1
Content-Type: application/json

{
  "title": "Changes",
  "author": "David Bowie",
  "year": 1971
}

### Update Book (not found)
PUT {{BookTracker.Api_HostAddress}}/books/9999
Content-Type: application/json

{
  "title": "Unknown Book",
  "author": "Unknown Author",
  "year": 2000
}

### Get Book by Id
GET {{BookTracker.Api_HostAddress}}/books/1

### Get Book by Id (not found)
GET {{BookTracker.Api_HostAddress}}/books/9999

### Get Books Page 1
GET {{BookTracker.Api_HostAddress}}/books?page=1&pageSize=10

### Get Books Page 2
GET {{BookTracker.Api_HostAddress}}/books?page=2&pageSize=10